using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Xml;
using System.Xml.Linq;
using System.Xml.XPath;
using Simple1C.Impl.Helpers;

namespace Generator
{
    public class CsProjectFileUpdater
    {
        private const string namespaceName = "http://schemas.microsoft.com/developer/msbuild/2003";
        private readonly string csprojFilePath;
        private readonly string autogeneratedSourcesPath;
        private readonly XmlNamespaceManager xmlNamespaceManager;

        public CsProjectFileUpdater(string csprojFilePath, string autogeneratedSourcesPath)
        {
            this.csprojFilePath = csprojFilePath;
            this.autogeneratedSourcesPath = autogeneratedSourcesPath;
            xmlNamespaceManager = new XmlNamespaceManager(new NameTable());
            xmlNamespaceManager.AddNamespace("ns", namespaceName);
        }

        public void Update()
        {
            XDocument xProjDocument;
            using (var fs = File.Open(csprojFilePath, FileMode.Open, FileAccess.Read))
                xProjDocument = XDocument.Load(fs);
            var autogeneratedCodeRelativePath = PathHelpers.GetRelativePath(csprojFilePath, autogeneratedSourcesPath);
            const string xpathFormat = "/ns:Project/ns:ItemGroup/ns:Compile[starts-with(@Include, \"{0}\")]";
            var xpath = string.Format(xpathFormat, autogeneratedCodeRelativePath);
            var csprojItems = xProjDocument
                .XPathSelectElements(xpath, xmlNamespaceManager)
                .Select(x => new
                {
                    item = x,
                    include = x.Attribute("Include").Value
                })
                .ToArray();
            XElement itemGroup;
            if (csprojItems.Length == 0)
            {
                var xProj = xProjDocument.Element(XName.Get("Project", namespaceName));
                if (xProj == null)
                    throw new InvalidOperationException("assertion failure");
                itemGroup = xProj.Elements(XName.Get("ItemGroup", namespaceName))
                    .FirstOrDefault();
                if (itemGroup == null)
                {
                    itemGroup = new XElement(XName.Get("ItemGroup", namespaceName));
                    xProj.Add(itemGroup);
                }
            }
            else
            {
                itemGroup = csprojItems[0].item.Parent;
                if (itemGroup == null)
                    throw new InvalidOperationException("assertion failure");
            }
            var currentFiles = Directory.Exists(autogeneratedSourcesPath)
                ? Directory.GetFiles(autogeneratedSourcesPath, "*.cs", SearchOption.AllDirectories)
                    .ToSet(StringComparer.OrdinalIgnoreCase)
                : new HashSet<string>();
            var csprojDirectoryPath = PathHelpers.GetDirectoryName(csprojFilePath);
            var itemsToDelete = csprojItems
                .Where(x => !currentFiles.Contains(Path.Combine(csprojDirectoryPath, x.include)))
                .ToArray();
            var csprojItemsSet = csprojItems
                .Select(x => x.include)
                .ToSet(StringComparer.OrdinalIgnoreCase);
            var csprojDirectoryPathLength = PathHelpers.IncludeTrailingDirectorySlash(csprojDirectoryPath).Length;
            var itemsToInsert = currentFiles
                .Select(x => new
                {
                    fullpath = x,
                    relativePath = x.Substring(csprojDirectoryPathLength)
                })
                .Where(x => !csprojItemsSet.Contains(x.relativePath))
                .Select(x => x.relativePath)
                .ToArray();
            foreach (var x in itemsToDelete)
                x.item.Remove();
            foreach (var x in itemsToInsert)
                itemGroup.Add(new XElement(XName.Get("Compile", namespaceName),
                    new XAttribute("Include", x)));
            using (var fs = File.Open(csprojFilePath, FileMode.Truncate, FileAccess.Write))
                xProjDocument.Save(fs);
        }
    }
}